# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty


# Setup
title:               Selenium Code Snippets
tagline:             'for lazy tester'
description:         'A collection of code snippets for lazy automation tester.'
url:                 http://yatheeshraju.github.io
baseurl:             '/Selenium-Code-Snippets'
paginate:            3

# About/contact
author:
  name:              Yatheesh Raju
  url:               
  email:             

# Custom vars
version:             1.0.0
